duck:
  hh: 21
  hl: 0
  sh: 255
  sl: 220
  vh: 255
  vl: 200
lane_image:
  bottom_right_x: 638
  bottom_right_y: 470
  bottom_left_x: 0
  bottom_left_y: 470
  top_left_x: 75
  top_left_y: 300
  top_right_x: 545
  top_right_y: 300
white:
  hl: 0
  hh: 255
  sl: 0
  sh: 79
  vl: 118
  vh: 255
gelb:
  hl: 19
  hh: 38
  sl: 93
  sh: 255
  vl: 110
  vh: 208
v_min: 0.15
v_max: 0.3


