lane_image:
  bottom_right_x: 600
  bottom_right_y: 470
  bottom_left_x: 40
  bottom_left_y: 470
  top_left_x: 240
  top_left_y: 240
  top_right_x: 370
  top_right_y: 240

min_distance_nearestDuckie: 330

show_image: false